### ISSUE TITLE
Wrong input elements type

### ISSUE THREAD

**Issue by M7Arman** [Hasmikus/Hasmik-s-repository#1]
Why **'First name'** and **'Last name'** `<input>` elements have number type?

**Comment by Hasmikus** [comment]
Look at  the file now, please. There is a new commit.

**Comment by M7Arman** [comment]
it would be better if you put the last commit link here.

**Comment by Hasmikus** [comment]
https://github.com/Hasmikus/Hasmik-s-repository/commit/5e2bc2894f084f48807e9e3b4fb4927daee1070e

**Comment by M7Arman** [comment]
Okay. Now, you can close this issue.
